import React from 'react';
import { 
  Shield, AlertTriangle, XCircle, CheckCircle, 
  Hash, FileText, Activity, Search, 
  ExternalLink, Clock, BarChart3, Download 
} from 'lucide-react';
import { formatFileSize, getThreatColor, getThreatBgColor } from '../utils/fileUtils';
import type { CompleteScanData } from '../types/scan';

interface ScanResultsProps {
  scanData: CompleteScanData;
  onNewScan: () => void;
}

export default function ScanResults({ scanData, onNewScan }: ScanResultsProps) {
  const { result, fileName, fileSize, sha256Hash, scanTimestamp } = scanData;

  const getVerdictIcon = (verdict: string) => {
    switch (verdict) {
      case 'safe':
        return <CheckCircle className="w-8 h-8 text-green-600" />;
      case 'suspicious':
        return <AlertTriangle className="w-8 h-8 text-yellow-600" />;
      case 'malicious':
      case 'critical':
        return <XCircle className="w-8 h-8 text-red-600" />;
      default:
        return <Shield className="w-8 h-8 text-gray-600" />;
    }
  };

  const getVerdictMessage = (verdict: string) => {
    switch (verdict) {
      case 'safe':
        return 'This file appears to be safe based on our analysis.';
      case 'suspicious':
        return 'This file has suspicious characteristics and should be handled with caution.';
      case 'malicious':
        return 'This file has been identified as malicious and should not be executed.';
      case 'critical':
        return 'This file poses a critical threat and should be quarantined immediately.';
      default:
        return 'Analysis completed with unknown result.';
    }
  };

  const downloadReport = () => {
    const reportData = {
      scanId: scanData.scanId,
      fileName: scanData.fileName,
      fileSize: scanData.fileSize,
      sha256Hash: scanData.sha256Hash,
      scanTimestamp: scanData.scanTimestamp,
      overallVerdict: result.overallVerdict,
      threatScore: result.threatScore,
      analysisResults: {
        hashCheck: result.hashCheckResult,
        heuristic: result.heuristicResult,
        staticAnalysis: result.staticAnalysisResult,
        behavioralAnalysis: result.behavioralAnalysisResult
      },
      externalSources: result.externalSources
    };

    const reportText = `
SafeScanX Security Analysis Report
==================================

File Information:
- Name: ${fileName}
- Size: ${formatFileSize(fileSize)}
- SHA-256: ${sha256Hash}
- Scan Date: ${new Date(scanTimestamp).toLocaleString()}

Overall Assessment:
- Verdict: ${result.overallVerdict.toUpperCase()}
- Threat Score: ${result.threatScore}/100
- Risk Level: ${result.overallVerdict}

Analysis Details:

1. Hash Database Check:
   ${result.hashCheckResult.found ? 
     `✓ Hash found in database
   Source: ${result.hashCheckResult.source}
   Verdict: ${result.hashCheckResult.verdict}` : 
     '✗ Hash not found in threat databases'}

2. Heuristic Analysis:
   ${result.heuristicResult.flags.length > 0 ? 
     `Flags: ${result.heuristicResult.flags.join(', ')}` : 
     'No heuristic flags detected'}

3. Static Analysis:
   ${result.staticAnalysisResult.detectedPatterns.length > 0 ? 
     `Detected Patterns: ${result.staticAnalysisResult.detectedPatterns.map(p => p.name).join(', ')}` : 
     'No malicious patterns detected'}

4. Behavioral Analysis:
   Verdict: ${result.behavioralAnalysisResult.verdict}
   ${result.behavioralAnalysisResult.note ? `Note: ${result.behavioralAnalysisResult.note}` : ''}

Generated by SafeScanX - Advanced Malware Detection System
Report ID: ${scanData.scanId}
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SafeScanX_Report_${fileName}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto space-y-6">
      {/* Overall Result */}
      <div className={`rounded-xl border-2 p-6 ${getThreatBgColor(result.overallVerdict)} border-current`}>
        <div className="flex items-start justify-between">
          <div className="flex items-center space-x-4">
            {getVerdictIcon(result.overallVerdict)}
            <div>
              <h2 className={`text-2xl font-bold capitalize ${getThreatColor(result.overallVerdict)}`}>
                {result.overallVerdict}
              </h2>
              <p className="text-gray-700 mt-1">{getVerdictMessage(result.overallVerdict)}</p>
            </div>
          </div>
          
          <div className="text-right">
            <div className={`text-3xl font-bold ${getThreatColor(result.overallVerdict)}`}>
              {result.threatScore}/100
            </div>
            <p className="text-sm text-gray-600">Threat Score</p>
          </div>
        </div>
      </div>

      {/* File Information */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
        <div className="p-6 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900 flex items-center">
            <FileText className="w-5 h-5 mr-2" />
            File Information
          </h3>
        </div>
        <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">File Name</label>
            <p className="mt-1 text-gray-900 font-mono">{fileName}</p>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">File Size</label>
            <p className="mt-1 text-gray-900">{formatFileSize(fileSize)}</p>
          </div>
          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700">SHA-256 Hash</label>
            <p className="mt-1 text-gray-900 font-mono text-sm break-all">{sha256Hash}</p>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Scan Time</label>
            <p className="mt-1 text-gray-900">{new Date(scanTimestamp).toLocaleString()}</p>
          </div>
        </div>
      </div>

      {/* Analysis Results */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Hash Database Check */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center">
              <Hash className="w-5 h-5 mr-2" />
              Hash Database Check
            </h3>
          </div>
          <div className="p-6">
            {result.hashCheckResult.found ? (
              <div className="space-y-3">
                <div className="flex items-center space-x-2">
                  <CheckCircle className="w-4 h-4 text-green-600" />
                  <span className="text-green-700 font-medium">Hash found in database</span>
                </div>
                <div className="text-sm text-gray-600">
                  <p><strong>Source:</strong> {result.hashCheckResult.source}</p>
                  <p><strong>Verdict:</strong> <span className={getThreatColor(result.hashCheckResult.verdict)}>{result.hashCheckResult.verdict}</span></p>
                  {result.hashCheckResult.lastSeen && (
                    <p><strong>Last Seen:</strong> {new Date(result.hashCheckResult.lastSeen).toLocaleDateString()}</p>
                  )}
                  {result.hashCheckResult.scanCount && (
                    <p><strong>Scan Count:</strong> {result.hashCheckResult.scanCount}</p>
                  )}
                </div>
              </div>
            ) : (
              <div className="flex items-center space-x-2">
                <Search className="w-4 h-4 text-gray-400" />
                <span className="text-gray-600">Hash not found in threat databases</span>
              </div>
            )}
          </div>
        </div>

        {/* Heuristic Analysis */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center">
              <BarChart3 className="w-5 h-5 mr-2" />
              Heuristic Analysis
            </h3>
          </div>
          <div className="p-6">
            <div className="space-y-3">
              {result.heuristicResult.flags.length > 0 ? (
                <div>
                  <h4 className="font-medium text-gray-900 mb-2">Detected Flags:</h4>
                  <ul className="space-y-1">
                    {result.heuristicResult.flags.map((flag, index) => (
                      <li key={index} className="text-sm text-gray-600 flex items-start">
                        <AlertTriangle className="w-3 h-3 text-yellow-500 mr-2 mt-0.5 flex-shrink-0" />
                        {flag}
                      </li>
                    ))}
                  </ul>
                </div>
              ) : (
                <p className="text-gray-600">No heuristic flags detected</p>
              )}
            </div>
          </div>
        </div>

        {/* Static Analysis */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center">
              <FileText className="w-5 h-5 mr-2" />
              Static Analysis
            </h3>
          </div>
          <div className="p-6">
            <div className="space-y-3">
              {result.staticAnalysisResult.detectedPatterns.length > 0 ? (
                <div>
                  <h4 className="font-medium text-gray-900 mb-2">Detected Patterns:</h4>
                  <ul className="space-y-2">
                    {result.staticAnalysisResult.detectedPatterns.map((pattern, index) => (
                      <li key={index} className="text-sm">
                        <div className="flex items-center justify-between">
                          <span className="font-medium text-gray-900">{pattern.name}</span>
                          <span className={`px-2 py-1 rounded-full text-xs ${
                            pattern.severity === 'critical' ? 'bg-red-100 text-red-800' :
                            pattern.severity === 'high' ? 'bg-orange-100 text-orange-800' :
                            pattern.severity === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-blue-100 text-blue-800'
                          }`}>
                            {pattern.severity}
                          </span>
                        </div>
                        <p className="text-gray-600 mt-1">Matches: {pattern.matches}</p>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : (
                <p className="text-gray-600">No malicious patterns detected</p>
              )}
            </div>
          </div>
        </div>

        {/* Behavioral Analysis */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center">
              <Activity className="w-5 h-5 mr-2" />
              Behavioral Analysis
            </h3>
          </div>
          <div className="p-6">
            <div className="space-y-3">
              <div className="flex items-center space-x-3">
                {result.behavioralAnalysisResult.verdict === 'safe' ? (
                  <CheckCircle className="w-6 h-6 text-green-600" />
                ) : result.behavioralAnalysisResult.verdict === 'malicious' ? (
                  <XCircle className="w-6 h-6 text-red-600" />
                ) : result.behavioralAnalysisResult.verdict === 'suspicious' ? (
                  <AlertTriangle className="w-6 h-6 text-yellow-600" />
                ) : (
                  <Activity className="w-6 h-6 text-gray-600" />
                )}
                <span className={`text-lg font-semibold capitalize ${getThreatColor(result.behavioralAnalysisResult.verdict)}`}>
                  {result.behavioralAnalysisResult.verdict}
                </span>
              </div>
              
              {result.behavioralAnalysisResult.note && (
                <p className="text-sm text-gray-600">{result.behavioralAnalysisResult.note}</p>
              )}
              
              {result.behavioralAnalysisResult.behaviors && result.behavioralAnalysisResult.behaviors.length > 0 && (
                <div>
                  <h4 className="font-medium text-gray-900 mb-2">Observed Behaviors:</h4>
                  <ul className="space-y-1">
                    {result.behavioralAnalysisResult.behaviors.slice(0, 3).map((behavior, index) => (
                      <li key={index} className="text-sm text-gray-600">• {behavior}</li>
                    ))}
                  </ul>
                </div>
              )}
              
              {result.behavioralAnalysisResult.error && (
                <p className="text-red-600 text-sm">{result.behavioralAnalysisResult.error}</p>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* External Sources */}
      {Object.keys(result.externalSources).length > 0 && (
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center">
              <ExternalLink className="w-5 h-5 mr-2" />
              External Threat Intelligence
            </h3>
          </div>
          <div className="p-6 space-y-4">
            {Object.entries(result.externalSources).map(([source, data]) => (
              <div key={source}>
                <h4 className="font-medium text-gray-900 capitalize mb-2">{source}</h4>
                <div className="text-sm text-gray-600">
                  {typeof data === 'object' && data !== null ? (
                    <pre className="whitespace-pre-wrap text-xs bg-gray-50 p-3 rounded-lg overflow-x-auto">{JSON.stringify(data, null, 2)}</pre>
                  ) : (
                    <p className="bg-gray-50 p-3 rounded-lg">{String(data)}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex justify-center space-x-4">
        <button
          onClick={downloadReport}
          className="bg-green-600 hover:bg-green-700 text-white font-medium py-3 px-8 rounded-lg transition-colors duration-200 inline-flex items-center space-x-2"
        >
          <Download className="w-5 h-5" />
          <span>Download Report</span>
        </button>
        
        <button
          onClick={onNewScan}
          className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-8 rounded-lg transition-colors duration-200 inline-flex items-center space-x-2"
        >
          <Shield className="w-5 h-5" />
          <span>Scan Another File</span>
        </button>
      </div>
    </div>
  );
}